from typing import Any, Dict, List

def init(api_key: str, environment: str) -> None: ...
def list_indexes() -> List[str]: ...
def create_index(name: str, dimension: int, metric: str, **kwargs: Any) -> None: ...
def delete_index(name: str) -> None: ...
def describe_index(name: str) -> Any: ...

class Index:
    def upsert(self, vectors: List[Any], namespace: str | None = None) -> None: ...
    def query(self, vector: List[float] | None = None, sparse_vector: Dict[str, List[float]] | None = None, top_k: int = 5, include_metadata: bool = False) -> Any: ...
