top_k: 5
rrf_k: 60

# Compute device selection: auto chooses best available
device_preference: auto  # auto, cpu, gpu_openvino, gpu_xpu
# Numerical precision for inference and retrieval operations
precision: fp32          # fp32, fp16, int8

pinecone_dense_index: dense-index
pinecone_sparse_index: sparse-index

evaluation_thresholds:
  faithfulness: 0.7
  relevancy: 0.7
  precision: 0.7

performance_policy:
  target_p95_ms: 2000
  auto_tune_enabled: false
  max_top_k: 50
  rerank_disable_threshold: 1500
