from typing import Any

class Blocks:
    def __enter__(self) -> 'Blocks': ...
    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> None: ...

class Component:
    def change(self, *args: Any, **kwargs: Any) -> Any: ...
    def click(self, *args: Any, **kwargs: Any) -> Any: ...
    def update(self, *args: Any, **kwargs: Any) -> Any: ...

def State(value: Any = ...) -> Component: ...
def Accordion(label: str, open: bool = ...) -> Component: ...
def Slider(minimum: float = ..., maximum: float = ..., step: float = ..., value: Any = ..., label: str = ...) -> Component: ...
def Checkbox(value: bool = ..., label: str = ...) -> Component: ...
def Markdown(value: str = ...) -> Component: ...
def JSON(value: Any = ...) -> Component: ...
def Row() -> Component: ...
def Button(value: str = ..., variant: str = ...) -> Component: ...
def DownloadButton(label: str = ...) -> Component: ...
def Textbox(value: str = ..., label: str = ...) -> Component: ...
def Plot(value: Any = ...) -> Component: ...
def DataFrame(value: Any = ...) -> Component: ...
def File(label: str = ...) -> Component: ...
def Tabs() -> Component: ...
def Tab(label: str) -> Component: ...
def LinePlot(value: Any = ...) -> Component: ...

def ChatInterface(*args: Any, **kwargs: Any) -> Any: ...
def load(*args: Any, **kwargs: Any) -> Any: ...
def mount_gradio_app(*args: Any, **kwargs: Any) -> Any: ...
def update(*args: Any, **kwargs: Any) -> Any: ...
def empty() -> Any: ...
